FROM mcr.microsoft.com/dotnet/sdk:5.0
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development

WORKDIR /src/Services/Emailing.Service/Emailing.Service.API
ENTRYPOINT dotnet watch run --no-launch-profile -c Debug