FROM mcr.microsoft.com/dotnet/sdk:5.0
ARG BUILD_CONFIGURATION=Debug
ENV DOTNET_ENVIRONMENT=Development

WORKDIR /src/Services/Workshop.Service/Workshop.Service.Workers
ENTRYPOINT dotnet watch run --no-launch-profile -c Debug