FROM mcr.microsoft.com/dotnet/sdk:5.0
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:5002
EXPOSE 5002

WORKDIR /app
ENTRYPOINT dotnet watch run --no-launch-profile -c Debug