CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE criteria (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description text NOT NULL,
    max_points integer NOT NULL,
    task_uid uuid NOT NULL,
    CONSTRAINT "PK_criteria" PRIMARY KEY (id)
);

CREATE TABLE works (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    content text NULL,
    author_id integer NOT NULL,
    task_uid uuid NOT NULL,
    CONSTRAINT "PK_works" PRIMARY KEY (id)
);

CREATE TABLE reviews (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created timestamp with time zone NULL,
    modified timestamp with time zone NULL,
    reviewer_id integer NOT NULL,
    work_id integer NOT NULL,
    CONSTRAINT "PK_reviews" PRIMARY KEY (id),
    CONSTRAINT "FK_reviews_works_work_id" FOREIGN KEY (work_id) REFERENCES works (id) ON DELETE CASCADE
);

CREATE TABLE grades (
    review_id integer NOT NULL,
    criterion_id integer NOT NULL,
    points integer NULL,
    feedback text NULL,
    CONSTRAINT "PK_grades" PRIMARY KEY (review_id, criterion_id),
    CONSTRAINT "FK_grades_criteria_criterion_id" FOREIGN KEY (criterion_id) REFERENCES criteria (id) ON DELETE CASCADE,
    CONSTRAINT "FK_grades_reviews_review_id" FOREIGN KEY (review_id) REFERENCES reviews (id) ON DELETE CASCADE
);

CREATE INDEX "IX_grades_criterion_id" ON grades (criterion_id);

CREATE INDEX "IX_reviews_work_id" ON reviews (work_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210529120748_InitialModel', '5.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE reviews DROP CONSTRAINT "FK_reviews_works_work_id";

DROP TABLE works;

CREATE TABLE submissions (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    content text NULL,
    author_id text NULL,
    workshop_uid uuid NOT NULL,
    CONSTRAINT "PK_submissions" PRIMARY KEY (id)
);

ALTER TABLE reviews ADD CONSTRAINT "FK_reviews_submissions_work_id" FOREIGN KEY (work_id) REFERENCES submissions (id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210612165957_RenameWorkToSubmission', '5.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE reviews DROP CONSTRAINT "FK_reviews_submissions_work_id";

ALTER TABLE reviews RENAME COLUMN work_id TO submission_id;

ALTER INDEX "IX_reviews_work_id" RENAME TO "IX_reviews_submission_id";

ALTER TABLE reviews ADD CONSTRAINT "FK_reviews_submissions_submission_id" FOREIGN KEY (submission_id) REFERENCES submissions (id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210612170758_RenameWorkIdColumnToSumissionId', '5.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE criteria RENAME COLUMN task_uid TO workshop_uid;

ALTER TABLE reviews ALTER COLUMN reviewer_id TYPE character varying(255);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210613113738_RenameTaskToWorkshopInCriteria', '5.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE submissions ADD author character varying(255) NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210710175629_AddAuthorColumnToSubmissionsTable', '5.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE reviews ADD reviewer character varying(255) NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210710204949_AddReviewerColumnToReviewsTable', '5.0.6');

COMMIT;

START TRANSACTION;

CREATE TABLE review_deadlines (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    uid uuid NOT NULL,
    review_start timestamp with time zone NOT NULL,
    review_end timestamp with time zone NOT NULL,
    instructor_id character varying(255) NOT NULL,
    CONSTRAINT "PK_review_deadlines" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210712181304_CreateSubmissionsDeadlinesTable', '5.0.6');

COMMIT;

