CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE tasks (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    link uuid NOT NULL,
    submission_start timestamp with time zone NOT NULL,
    submission_end timestamp with time zone NOT NULL,
    review_start timestamp with time zone NOT NULL,
    review_end timestamp with time zone NOT NULL,
    published timestamp with time zone NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    "InstructorId" integer NOT NULL,
    CONSTRAINT "PK_tasks" PRIMARY KEY (id)
);

CREATE TABLE criteria (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description text NOT NULL,
    max_points integer NOT NULL,
    task_id integer NOT NULL,
    CONSTRAINT "PK_criteria" PRIMARY KEY (id),
    CONSTRAINT "FK_criteria_tasks_task_id" FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE
);

CREATE INDEX "IX_criteria_task_id" ON criteria (task_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210522181331_InitialModel', '5.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE tasks ALTER COLUMN modified DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210522212359_SetModifiedColumnToNullable', '5.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE tasks RENAME COLUMN link TO uid;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210523142617_RenameLinkToUidInTasksTable', '5.0.6');

COMMIT;

START TRANSACTION;

CREATE UNIQUE INDEX "IX_tasks_uid" ON tasks (uid);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210523142929_CreateUniqueIndexOnUidInTaskTable', '5.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE tasks RENAME COLUMN "InstructorId" TO instructor_id;

CREATE TABLE participant (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT "PK_participant" PRIMARY KEY (id)
);

CREATE TABLE task_participants (
    task_id integer NOT NULL,
    participant_id integer NOT NULL,
    CONSTRAINT "PK_task_participants" PRIMARY KEY (task_id, participant_id),
    CONSTRAINT "FK_task_participants_tasks_task_id" FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT "FK_task_participants_participant_participant_id" FOREIGN KEY (participant_id) REFERENCES participant (id) ON DELETE CASCADE
);

CREATE INDEX "IX_task_participants_task_id" ON task_participants (task_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210524220214_AddParticipantsAndTaskParticipantsTables', '5.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE task_participants DROP CONSTRAINT "FK_task_participants_participant_participant_id";

ALTER TABLE participant DROP CONSTRAINT "PK_participant";

ALTER TABLE participant RENAME TO participants;

ALTER TABLE participants ADD CONSTRAINT "PK_participants" PRIMARY KEY (id);

ALTER TABLE task_participants ADD CONSTRAINT "FK_task_participants_participants_participant_id" FOREIGN KEY (participant_id) REFERENCES participants (id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210527190629_RenameParticipantToParticipants', '5.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE tasks ALTER COLUMN instructor_id TYPE character varying(255);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210531163228_AlterInstructorIdDataTypeToString', '5.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE participants ADD auth0_id text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210531164916_AddAuth0IdColumnToParticipants', '5.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE participants ADD email character varying(255) NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210603225152_AddEmailFieldToParticipants', '5.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE participants ALTER COLUMN auth0_id TYPE character varying(255);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210606125106_ChnageAuth0_idIntoVarChar255', '5.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE criteria DROP CONSTRAINT "FK_criteria_tasks_task_id";

DROP TABLE task_participants;

DROP TABLE tasks;

ALTER TABLE criteria RENAME COLUMN task_id TO workshop_id;

ALTER INDEX "IX_criteria_task_id" RENAME TO "IX_criteria_workshop_id";

CREATE TABLE workshops (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    uid uuid NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    submission_start timestamp with time zone NOT NULL,
    submission_end timestamp with time zone NOT NULL,
    review_start timestamp with time zone NOT NULL,
    review_end timestamp with time zone NOT NULL,
    published timestamp with time zone NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NULL,
    instructor_id character varying(255) NOT NULL,
    CONSTRAINT "PK_workshops" PRIMARY KEY (id)
);

CREATE TABLE workshop_participants (
    participant_id integer NOT NULL,
    workshop_id integer NOT NULL,
    CONSTRAINT "PK_workshop_participants" PRIMARY KEY (participant_id, workshop_id),
    CONSTRAINT "FK_workshop_participants_participants_participant_id" FOREIGN KEY (participant_id) REFERENCES participants (id) ON DELETE CASCADE,
    CONSTRAINT "FK_workshop_participants_workshops_workshop_id" FOREIGN KEY (workshop_id) REFERENCES workshops (id) ON DELETE CASCADE
);

CREATE INDEX "IX_workshop_participants_workshop_id" ON workshop_participants (workshop_id);

CREATE UNIQUE INDEX "IX_workshops_uid" ON workshops (uid);

ALTER TABLE criteria ADD CONSTRAINT "FK_criteria_workshops_workshop_id" FOREIGN KEY (workshop_id) REFERENCES workshops (id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210608150543_RenameTaskToWorkshop', '5.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE workshops ADD number_of_reviews integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210615183535_AddNumberOfReviewsColumn', '5.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE workshops ADD instructor character varying(255) NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210710073858_AddInstructorColumnToWorkshopTable', '5.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE participants ADD name character varying(255) NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210710154630_AddNameColumnToParticipantsTable', '5.0.6');

COMMIT;

