FROM mcr.microsoft.com/dotnet/sdk:5.0
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:80
# ENV ASPNETCORE_URLS=http://+:5000
# EXPOSE 5000

WORKDIR /src/Services/Workshop.Service/Workshop.Service.API
ENTRYPOINT dotnet run --no-launch-profile -c Debug