FROM mcr.microsoft.com/dotnet/sdk:5.0
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:80
# ENV ASPNETCORE_URLS=http://+:5001
# EXPOSE 5001

WORKDIR /src/Services/Submission.Service/Submission.Service.API
ENTRYPOINT dotnet watch run --no-launch-profile -c Debug