// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Task.Service.API.Persistence.Contexts;

namespace Task.Service.API.Migrations
{
        [DbContext(typeof(TaskContext))]
        partial class TaskContextModelSnapshot : ModelSnapshot
        {
                protected override void BuildModel(ModelBuilder modelBuilder)
                {
#pragma warning disable 612, 618
                        modelBuilder
                            .HasAnnotation("Relational:MaxIdentifierLength", 63)
                            .HasAnnotation("ProductVersion", "5.0.6")
                            .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                        modelBuilder.Entity("Task.Service.API.Domain.Models.Criterion", b =>
                            {
                                    b.Property<int>("Id")
                            .ValueGeneratedOnAdd()
                            .HasColumnType("integer")
                            .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                                    b.Property<string>("Description")
                            .IsRequired()
                            .HasColumnType("text");

                                    b.Property<int>("MaxPoints")
                            .HasColumnType("integer");

                                    b.Property<int>("TaskId")
                            .HasColumnType("integer");

                                    b.HasKey("Id");

                                    b.HasIndex("TaskId");

                                    b.ToTable("Criteria");
                            });

                        modelBuilder.Entity("Task.Service.API.Domain.Models.Task", b =>
                            {
                                    b.Property<int>("Id")
                            .ValueGeneratedOnAdd()
                            .HasColumnType("integer")
                            .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                                    b.Property<DateTimeOffset>("Created")
                            .HasColumnType("timestamp with time zone");

                                    b.Property<string>("Description")
                            .IsRequired()
                            .HasColumnType("text");

                                    b.Property<int>("InstructorId")
                            .HasColumnType("integer");

                                    b.Property<Guid>("Link")
                            .HasColumnType("uuid");

                                    b.Property<DateTimeOffset>("Modified")
                            .HasColumnType("timestamp with time zone");

                                    b.Property<string>("Name")
                            .IsRequired()
                            .HasMaxLength(255)
                            .HasColumnType("character varying(255)");

                                    b.Property<DateTimeOffset>("Published")
                            .HasColumnType("timestamp with time zone");

                                    b.Property<DateTimeOffset>("ReviewEnd")
                            .HasColumnType("timestamp with time zone");

                                    b.Property<DateTimeOffset>("ReviewStart")
                            .HasColumnType("timestamp with time zone");

                                    b.Property<DateTimeOffset>("SubmissionEnd")
                            .HasColumnType("timestamp with time zone");

                                    b.Property<DateTimeOffset>("SubmissionStart")
                            .HasColumnType("timestamp with time zone");

                                    b.HasKey("Id");

                                    b.ToTable("Tasks");
                            });

                        modelBuilder.Entity("Task.Service.API.Domain.Models.Criterion", b =>
                            {
                                    b.HasOne("Task.Service.API.Domain.Models.Task", null)
                            .WithMany("Criteria")
                            .HasForeignKey("TaskId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();
                            });

                        modelBuilder.Entity("Task.Service.API.Domain.Models.Task", b =>
                            {
                                    b.Navigation("Criteria");
                            });
#pragma warning restore 612, 618
                }
        }
}
