# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  workshopserviceapi:
    image: workshopserviceapi:debug
    build:
      context: .
      dockerfile: Services/Workshop.Service/Workshop.Service.API/Dockerfile.dev
    ports:
      - 5000:80
    volumes:
      - ./Services/Workshop.Service/Workshop.Service.API:/app
      - ./Services/Workshop.Service/Workshop.Service.Contracts:/Workshop.Service.Contracts
      - ~/.vsdbg:/remote_debugger:rw

  submissionserviceapi:
    image: submissionserviceapi:debug
    build:
      context: .
      dockerfile: Services/Submission.Service/Submission.Service.API/Dockerfile.dev
    ports:
      - 5001:80
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  reviewserviceapi:
    image: reviewserviceapi
    build:
      context: .
      dockerfile: Services/Review.Service/Review.Service.API/Dockerfile.dev
    ports:
      - 5002:80
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
