version: "3.4"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq

  taskserviceapi:
    image: taskserviceapi
    build:
      context: .
      dockerfile: Services/Task.Service/Task.Service.API/Dockerfile
    depends_on:
      - rabbitmq

  workserviceapi:
    image: workserviceapi
    build:
      context: .
      dockerfile: Services/Work.Service/Work.Service.API/Dockerfile
    depends_on:
      - rabbitmq

  reviewserviceapi:
    image: reviewserviceapi
    build:
      context: .
      dockerfile: Services/Review.Service/Review.Service.API/Dockerfile

  webclient:
    image: webclient
    build:
      context: .
      dockerfile: Web/Dockerfile
